---
title: "Covid-19"
subtitle: "Infected cases worldwide"
author: "Gabriel Cabrera"
date: "09-06-2020"
output: 
  pdf_document:
    dev: cairo_pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r echo=FALSE, message=FALSE}
library("tidyverse")
library("hrbrthemes")
library("mapdata")
library("magrittr")
library("lubridate")
```

```{r}
# world data 
world_map <- map_data("world") %>% 
  as_tibble() %>% 
  mutate(region = recode(region, 
                         "USA" = "United States of America",
                         "UK" = "United Kingdom",
                         "Tanzania" = "United Republic of Tanzania",
                         "Tobago" = "Trinidad and Tobago",
                         "Ivory Coast" = "Cote dIvoire",
                         "Turks and Caicos Islands" = "Turks and Caicos islands",
                         "Virgin Islands" = "United States Virgin Islands",
                         "Saint Vincent" = "Saint Vincent and the Grenadines",
                         "Republic of Congo" = "Congo"))
```

```{r}
# country in world 
country_in_world <- world_map %>% 
  select(region) %>% 
  distinct()
```

```{r}
# covid 19 data per country
covid_tbl <- readxl::read_xlsx("COVID-19.xlsx")
```

```{r}
# wrangling data
covid_total_cases <- covid_tbl %>%
  janitor::clean_names() %>% 
  mutate(date_rep = as.Date(date_rep)) %>% 
  group_by(countries_and_territories) %>% 
  mutate(total_cases = sum(cases),
         total_deaths = sum(deaths)) %>% 
  filter(date_rep == "2020-06-08") %>% 
  ungroup() %>% 
  select(countries_and_territories, 
         countryterritory_code, 
         total_cases, 
         total_deaths) %>% 
  rename(region = countries_and_territories,
         iso_code = countryterritory_code) %>% 
  mutate(contagion = case_when(
    is.na(total_cases)  ~ "Sin contagio",
    total_cases >= 0 & total_cases < 50000 ~ "0 - 50k",
    total_cases >= 50000 & total_cases < 100000 ~ "50k - 100k",
    total_cases >= 100000 & total_cases < 200000 ~ "100k - 200k",
    total_cases >= 200000 & total_cases < 400000 ~ "200k - 400k",
    total_cases >= 400000 & total_cases < 800000 ~ "400k - 800k",
    total_cases >= 800000 ~ "800k or more"
  ),
  contagion = factor(contagion, 
                     levels = c("Sin contagio",
                                "0 - 50k", 
                                "50k - 100k", 
                                "100k - 200k", 
                                "200k - 400k",
                                "400k - 800k",
                                "800k or more")))
```

```{r}
# function to clean coutnry names 
clean_country <- function(x) {
  
  country_name <- stringr::str_replace_all(x, "_", " ")

  return(country_name)
  
}
```

```{r}
covid_total_cases %<>%
  mutate_at(vars(region), list(~ clean_country(.)))
```

```{r}
country_in_covid <- covid_total_cases %>% 
  select(region) %>% 
  distinct()
```

```{r}
# verify difference in region variable 
diff_region <- setdiff(country_in_covid$region, country_in_world$region)
```

```{r}
# merge map world with covid 19 data
world_covid <- inner_join(covid_total_cases, world_map, by = "region")
```

```{r}
# leyend title
legend_title <- "COVID-19 infected cases worldwide"
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=10, fig.width=12}
ggplot() + 
  coord_fixed(1.3) +
  geom_polygon(data = world_covid,
               aes(x = long, y = lat, group = group, fill = contagion)) +
  geom_path(data = world_covid, 
            aes(x = long, y = lat, group = group, fill = contagion),
            color = "grey70", size = 0.1) +
  labs(title = "Mapping the coronavirus outbreak",
       subtitle = "As of 2.23pm June 8 BST",
       x = "",
       y = "",
       caption = "Graphic: Gabriel Cabrera G. \nSources: ECDC; Covid Tracking Project \n@GaboC_g") +
  guides(fill = guide_legend(title.position = "top", 
                             title.hjust = 0.5, 
                             nrow = 1,
                             label.position = "bottom")) + 
  scale_fill_manual(values = c("#d3e8f0", "#fae1af", 
                               "#fdac7a", "#f6736b", 
                               "#de526f", "#a90773"),
                    name = legend_title) +
  scale_color_manual(values = c("#d3e8f0", "#fae1af", 
                                "#fdac7a", "#f6736b", 
                                "#de526f", "#a90773"),
                     name = legend_title) +
  theme_ipsum(ticks = FALSE) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        plot.title = element_text(size = 18),
        plot.subtitle = element_text(size = 16),
        plot.caption = element_text(size = 14,
                                    face = "plain",
                                    hjust = 0,
                                    margin = margin(t = 1, unit = "cm")),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
```

```{r}
covid_total_deaths <- covid_tbl %>% 
  janitor::clean_names() %>% 
  mutate(date_rep = as.Date(date_rep)) %>% 
  group_by(countries_and_territories) %>% 
  filter(date_rep >= 2020-15-03) %>% 
  ungroup() %>% 
  select(date_rep,
         countries_and_territories, 
         countryterritory_code, 
         deaths,
         continent_exp) %>% 
  rename(region = countries_and_territories,
         iso_code = countryterritory_code)
```

